### ISSUE TITLE
panic occured when wrap go-playground./validator's errors

### ISSUE THREAD

**Issue by izumin5210** [srvc/fail#22]
from v4.0.0

```go
package main

import (
	"fmt"

	"github.com/srvc/fail"
	validator "gopkg.in/go-playground/validator.v9"
)

func main() {
	err := validator.ValidationErrors{}
	fmt.Println(fail.Wrap(err))
}
```

```
panic: runtime error: comparing uncomparable type validator.ValidationErrors

goroutine 1 [running]:
github.com/srvc/fail.extractPkgError(0x1be6a0, 0x40cfe0, 0x450230, 0x277c00)
	/go/src/github.com/srvc/fail/pkgerrors.go:82 +0x960
github.com/srvc/fail.convertPkgError(0x1be6a0, 0x40cfe0, 0x1901c0, 0x9f442304)
	/go/src/github.com/srvc/fail/pkgerrors.go:22 +0x40
github.com/srvc/fail.Unwrap(0x1be6a0, 0x40cfe0, 0x15e901, 0x7622)
	/go/src/github.com/srvc/fail/error.go:113 +0x260
github.com/srvc/fail.Wrap(0x1be6a0, 0x40cfe0, 0x0, 0x0, 0x0, 0x4423a0, 0x0, 0x0)
	/go/src/github.com/srvc/fail/error.go:85 +0x40
main.main()
	/go/src/29f35e98-5c00-4964-a695-ff39d667e9e2/main.go:12 +0xa0
```

**Comment by izumin5210** [comment]
minimum reproducible code

```go
package main

import (
	"fmt"
)

type Errors []error

func (errs Errors) Error() string { return "" }

func main() {
	var err error = Errors{}
	rootErr := err

	fmt.Println(rootErr == err) // panic: runtime error: comparing uncomparable type main.Errors

}
```

https://play.golang.org/p/Nv_8RybxmXN
